[package]
name = "rust_version_util"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
env_logger = "0.11.7"
r2d2 = "0.8.10"
r2d2_sqlite = "0.27.0"
rusqlite = "0.34.0"
serde = { version = "1", features = ["derive"] }
tera = "1"
